const SRV_HELLO_MSG_IND = 0
const SRV_CREATE_PASSENGER_REQ = 1
const SRV_CREATE_PASSENGER_RESP = 2
const SRV_CREATE_DRIVER_REQ = 3
const SRV_CREATE_DRIVER_RESP = 4
const SRV_LOGIN_PASSENGER_REQ = 5
const SRV_LOGIN_PASSENGER_RESP = 6
const SRV_LOGIN_DRIVER_REQ = 7
const SRV_LOGIN_DRIVER_RESP = 8
const SRV_DRIVER_ONLINE_REQ = 9
const SRV_DRIVER_ONLINE_RESP = 10
const SRV_POS_UPDATE_REQ = 11
const SRV_POS_UPDATE_RESP = 12
const SRV_ORDER_CAR_REQ = 13
const SRV_ORDER_CAR_RESP = 14
const SRV_JOB_IND = 15
const SRV_GET_JOB_REQ = 16
const SRV_GET_JOB_RESP = 17

export const Request = {
	SRV_CREATE_PASSENGER_REQ: 1,
	SRV_CREATE_DRIVER_REQ: 3,
	SRV_LOGIN_PASSENGER_REQ: 5,
	SRV_LOGIN_DRIVER_REQ: 7,
	SRV_DRIVER_ONLINE_REQ: 9,
	SRV_POS_UPDATE_REQ: 11,
	SRV_ORDER_CAR_REQ: 13,
	SRV_GET_JOB_REQ: 16
}

export const Response = {
	SRV_CREATE_PASSENGER_RESP: 2,
	SRV_CREATE_DRIVER_RESP: 4,
	SRV_LOGIN_PASSENGER_RESP: 6,
	SRV_LOGIN_DRIVER_RESP: 8,
	SRV_DRIVER_ONLINE_RESP: 10,
	SRV_POS_UPDATE_RESP: 12,
	SRV_ORDER_CAR_RESP: 14,
	SRV_GET_JOB_RESP: 17
}
